import { prisma } from './lib/prisma'

export async function seedDatabase(): Promise<void> {
  console.log('🌱 Iniciando seed...')

  await prisma.appConfig.upsert({
    where: { key: 'minimum_wage' },
    update: {},
    create: { key: 'minimum_wage', value: '1412.00' },
  })
  await prisma.appConfig.upsert({
    where: { key: 'minimum_wage_updated_at' },
    update: {},
    create: { key: 'minimum_wage_updated_at', value: new Date().toISOString() },
  })

  const phases = [
    { id: 0, slug: 'tutorial', name: 'Tutorial', title: 'O Despertar', color: 'gray', subtitle: 'Do zero ao primeiro passo real', orderIndex: 0, achievementName: 'Primeiro Passo', achievementIcon: '🌱', description: 'O início absoluto. Sem investimentos, sem estrutura. O objetivo é eliminar obstáculos, abrir as portas certas e dar o primeiro passo concreto.', flavorText: 'Todo herói começa sem nada. A diferença é que ele começa.' },
    { id: 1, slug: 'recruta', name: 'Recruta', title: 'Plantando a Semente', color: 'green', subtitle: 'De R$ 1 a R$ 10.000', orderIndex: 1, achievementName: 'Semente Plantada', achievementIcon: '🌿', description: 'Os números são pequenos. Os rendimentos mal aparecem. Essa fase é um teste de caráter, não de dinheiro. Quem sobrevive aqui sobrevive em qualquer fase.', flavorText: 'A semente que ninguém vê é a que vira floresta.' },
    { id: 2, slug: 'soldado', name: 'Soldado', title: 'Construindo a Base', color: 'blue', subtitle: 'De R$ 10.000 a R$ 50.000', orderIndex: 2, achievementName: 'Fundação Sólida', achievementIcon: '⚔️', description: 'O portfólio tem forma real. Os rendimentos aparecem nas notificações. A estratégia começa a existir. Disciplina é 90% do trabalho aqui.', flavorText: 'Um soldado não precisa de sorte. Precisa de disciplina.' },
    { id: 3, slug: 'veterano', name: 'Veterano', title: 'A Grande Escalada', color: 'teal', subtitle: 'De R$ 50.000 a R$ 100.000', orderIndex: 3, achievementName: 'Clube dos 100k', achievementIcon: '🛡️', description: 'A fase psicologicamente mais difícil. Os números sobem devagar e a sensação de "vai levar uma vida" bate forte. Mas R$ 100k é o verdadeiro ponto de não-retorno.', flavorText: 'Menos de 3% dos brasileiros chegam aqui. Você vai ser um deles.' },
    { id: 4, slug: 'elite', name: 'Elite', title: 'Primeiro Momentum', color: 'purple', subtitle: 'Do Clube dos 100k ao Ponto de Cruzamento', orderIndex: 4, achievementName: 'O Dinheiro Trabalha', achievementIcon: '🦅', description: 'O portfólio começa a trabalhar de verdade. Em meses bons, a valorização de um dia supera o aporte semanal. O dinheiro começa a chamar dinheiro.', flavorText: 'O momento em que o dinheiro trabalha mais do que você é o momento que muda tudo.' },
    { id: 5, slug: 'especialista', name: 'Especialista', title: 'A Máquina Ganha Vida', color: 'orange', subtitle: 'Renda passiva começa a ser sentida', orderIndex: 5, achievementName: 'Máquina Ativa', achievementIcon: '🔥', description: 'O Ponto de Cruzamento ficou para trás. O compounding agora é visível. A pressão de maximizar o aporte cede — a máquina tem vida própria.', flavorText: 'Você não precisa mais correr. A máquina já corre por você.' },
    { id: 6, slug: 'mestre', name: 'Mestre', title: 'Pré-Aposentado', color: 'yellow', subtitle: 'Trabalho vira opção, não obrigação', orderIndex: 6, achievementName: 'Trabalho é Opção', achievementIcon: '👑', description: 'Renda passiva cobre o básico. Você pode trabalhar meio período, mudar de área, virar freelancer — ou simplesmente reinvestir tudo e acelerar as fases finais.', flavorText: 'Trabalho deixa de ser o que você tem que fazer e vira o que você escolhe fazer.' },
    { id: 7, slug: 'heroi', name: 'Herói', title: 'Independência Financeira', color: 'amber', subtitle: 'Renda passiva sustenta 100% da vida', orderIndex: 7, achievementName: 'Financeiramente Livre', achievementIcon: '🏆', description: 'O portfólio cobre 100% das despesas. Trabalho é 100% opcional. A renda passiva cresce mesmo enquanto você vive bem.', flavorText: 'Você chegou. Trabalho é agora uma escolha, não uma necessidade.' },
    { id: 8, slug: 'lenda', name: 'Lenda', title: 'FIRE Completo', color: 'red', subtitle: 'Boss Final — Dono do Tempo', orderIndex: 8, achievementName: 'Dono do Tempo', achievementIcon: '💎', description: 'O jogo virou. Você não só vive dos rendimentos — o portfólio ainda CRESCE mesmo com você gastando confortavelmente. A riqueza se perpetua sozinha.', flavorText: 'O jogo não acaba — mas agora você escolhe o que jogar.' },
  ]

  for (const phase of phases) {
    await prisma.phase.upsert({ where: { id: phase.id }, update: phase, create: phase })
  }

  const missions = [
    { phaseId: 0, slug: 'eliminar-dividas', title: 'Eliminar dívidas de juros altos', missionType: 'behavioral', isRequiredForPhase: true, orderIndex: 1, targetValue: null, targetSmMultiple: null, requiredDurationDays: null, description: 'Quite cartão de crédito rotativo, cheque especial e empréstimos com juros acima de 1,5% ao mês. Enquanto essas dívidas existirem, qualquer investimento perde.' },
    { phaseId: 0, slug: 'abrir-corretora', title: 'Abrir conta em corretora ou banco de investimentos', missionType: 'behavioral', isRequiredForPhase: true, orderIndex: 2, targetValue: null, targetSmMultiple: null, requiredDurationDays: null, description: 'Crie sua conta em uma corretora séria. Não precisa aportar ainda — só abrir a conta e explorar a plataforma.' },
    { phaseId: 0, slug: 'primeiro-aporte', title: 'Fazer o primeiro aporte', missionType: 'portfolio_value', isRequiredForPhase: true, orderIndex: 3, targetValue: '0.01', targetSmMultiple: null, requiredDurationDays: null, description: 'Transfira qualquer valor para um investimento real. Pode ser R$ 10, qualquer coisa. O objetivo é quebrar a inércia.' },
    { phaseId: 0, slug: 'reserva-emergencia-inicial', title: 'Criar reserva de emergência inicial (1 mês)', missionType: 'behavioral', isRequiredForPhase: true, orderIndex: 4, targetValue: null, targetSmMultiple: null, requiredDurationDays: null, description: 'Separe o equivalente a 1 mês de gastos em conta com liquidez diária (CDB D+0, Tesouro Selic ou conta remunerada).' },
    { phaseId: 0, slug: 'educacao-3-tipos', title: 'Estudar pelo menos 3 tipos de investimento', missionType: 'behavioral', isRequiredForPhase: true, orderIndex: 5, targetValue: null, targetSmMultiple: null, requiredDurationDays: null, description: 'Entenda o básico de: Renda Fixa (CDB, Tesouro Direto, LCI/LCA), Renda Variável (ações, ETFs) e Fundos.' },
    { phaseId: 1, slug: 'meta-1k', title: 'Atingir R$ 1.000 investidos', missionType: 'portfolio_value', isRequiredForPhase: true, orderIndex: 1, targetValue: '1000.00', targetSmMultiple: null, requiredDurationDays: null, description: 'Primeiro marco numérico real. Representa um hábito já estabelecido.' },
    { phaseId: 1, slug: 'reserva-3-meses', title: 'Completar reserva de emergência: 3 meses de gastos', missionType: 'behavioral', isRequiredForPhase: true, orderIndex: 2, targetValue: null, targetSmMultiple: null, requiredDurationDays: null, description: 'Expanda a reserva para cobrir 3 meses completos. Sem isso, qualquer imprevisto força resgates na hora errada.' },
    { phaseId: 1, slug: 'aporte-fixo-automatico', title: 'Definir e automatizar aporte mensal fixo', missionType: 'behavioral', isRequiredForPhase: true, orderIndex: 3, targetValue: null, targetSmMultiple: null, requiredDurationDays: null, description: 'Estabeleça um valor e automatize a transferência logo após receber. Pague-se primeiro.' },
    { phaseId: 1, slug: 'dois-tipos-ativos', title: 'Ter pelo menos 2 tipos diferentes de ativos', missionType: 'behavioral', isRequiredForPhase: true, orderIndex: 4, targetValue: null, targetSmMultiple: null, requiredDurationDays: null, description: 'Ex: renda fixa + uma ação, ou Tesouro Direto + ETF.' },
    { phaseId: 1, slug: 'meta-10k', title: 'Atingir R$ 10.000 investidos', missionType: 'portfolio_value', isRequiredForPhase: true, orderIndex: 5, targetValue: '10000.00', targetSmMultiple: null, requiredDurationDays: null, description: 'Marco histórico: o portfólio começa a ter relevância real.' },
    { phaseId: 2, slug: 'reserva-6-meses', title: 'Completar reserva de emergência: 6 meses de gastos', missionType: 'behavioral', isRequiredForPhase: true, orderIndex: 1, targetValue: null, targetSmMultiple: null, requiredDurationDays: null, description: '6 meses protegidos. A partir daqui você investe com mais convicção.' },
    { phaseId: 2, slug: 'aporte-consistente', title: 'Aporte mensal consistente e crescente', missionType: 'behavioral', isRequiredForPhase: true, orderIndex: 2, targetValue: null, targetSmMultiple: null, requiredDurationDays: null, description: 'Mantenha aportes mensais e busque aumentar o valor gradualmente. Consistência vale mais que valor absoluto.' },
    { phaseId: 2, slug: 'tres-ativos-duas-categorias', title: 'Ter pelo menos 3 ativos em 2 categorias distintas', missionType: 'behavioral', isRequiredForPhase: true, orderIndex: 3, targetValue: null, targetSmMultiple: null, requiredDurationDays: null, description: 'Ex: 2 ações + 1 CDB, ou 1 ETF + 1 ação + 1 título público.' },
    { phaseId: 2, slug: 'meta-25k', title: 'Atingir R$ 25.000 investidos', missionType: 'portfolio_value', isRequiredForPhase: true, orderIndex: 4, targetValue: '25000.00', targetSmMultiple: null, requiredDurationDays: null, description: 'Metade do caminho para os R$ 50k.' },
    { phaseId: 2, slug: 'estrategia-alocacao', title: 'Documentar estratégia de alocação por categoria', missionType: 'behavioral', isRequiredForPhase: true, orderIndex: 5, targetValue: null, targetSmMultiple: null, requiredDurationDays: null, description: 'Escreva qual % você quer em cada categoria. Ter isso escrito evita decisões emocionais em quedas.' },
    { phaseId: 2, slug: 'meta-50k', title: 'Atingir R$ 50.000 investidos', missionType: 'portfolio_value', isRequiredForPhase: true, orderIndex: 6, targetValue: '50000.00', targetSmMultiple: null, requiredDurationDays: null, description: 'A base está construída.' },
    { phaseId: 3, slug: 'aporte-10-porcento', title: 'Aportar pelo menos 10% da renda bruta mensalmente', missionType: 'behavioral', isRequiredForPhase: true, orderIndex: 1, targetValue: null, targetSmMultiple: null, requiredDurationDays: null, description: '10% é o mínimo histórico para acumulação sólida de longo prazo.' },
    { phaseId: 3, slug: 'cinco-ativos-com-analise', title: 'Ter pelo menos 5 ativos com análise própria de cada um', missionType: 'behavioral', isRequiredForPhase: true, orderIndex: 2, targetValue: null, targetSmMultiple: null, requiredDurationDays: null, description: 'Para cada ativo: saber por que comprou, quais são os riscos e quando venderia.' },
    { phaseId: 3, slug: 'meta-75k', title: 'Atingir R$ 75.000 investidos', missionType: 'portfolio_value', isRequiredForPhase: true, orderIndex: 3, targetValue: '75000.00', targetSmMultiple: null, requiredDurationDays: null, description: '75% do caminho para o Clube dos 100k.' },
    { phaseId: 3, slug: 'aportes-12-meses', title: 'Manter aportes mensais por 12 meses consecutivos', missionType: 'habit', isRequiredForPhase: true, orderIndex: 4, targetValue: null, targetSmMultiple: null, requiredDurationDays: 365, description: 'Um ano inteiro de aportes sem interrupção, independente de crise ou queda de mercado.' },
    { phaseId: 3, slug: 'meta-100k', title: 'Atingir R$ 100.000 investidos', missionType: 'portfolio_value', isRequiredForPhase: true, orderIndex: 5, targetValue: '100000.00', targetSmMultiple: null, requiredDurationDays: null, description: 'O marco mais simbólico do jogo. O compounding começa a ser sentido mensalmente.' },
    { phaseId: 4, slug: 'meta-150k', title: 'Atingir R$ 150.000 investidos', missionType: 'portfolio_value', isRequiredForPhase: true, orderIndex: 1, targetValue: '150000.00', targetSmMultiple: null, requiredDurationDays: null, description: 'O portfólio tem massa crítica. A diferença entre um mês bom e ruim já é de R$ 1.500–2.000 só em retorno.' },
    { phaseId: 4, slug: 'ativos-internacionais', title: 'Ter pelo menos 2 ativos internacionais na carteira', missionType: 'behavioral', isRequiredForPhase: true, orderIndex: 2, targetValue: null, targetSmMultiple: null, requiredDurationDays: null, description: 'ETFs globais ou equivalentes. Diversificação geográfica reduz dependência de um único país e moeda.' },
    { phaseId: 4, slug: 'plano-imovel', title: 'Registrar plano de imóvel próprio', missionType: 'behavioral', isRequiredForPhase: false, orderIndex: 3, targetValue: null, targetSmMultiple: null, requiredDurationDays: null, description: 'Defina uma data-alvo e valor estimado, ou registre conscientemente a decisão de não adquirir.' },
    { phaseId: 4, slug: 'meta-200k', title: 'Atingir R$ 200.000 investidos', missionType: 'portfolio_value', isRequiredForPhase: true, orderIndex: 4, targetValue: '200000.00', targetSmMultiple: null, requiredDurationDays: null, description: 'Dois terços do caminho para o Ponto de Cruzamento.' },
    { phaseId: 4, slug: 'ponto-cruzamento', title: 'Ponto de Cruzamento: retorno mensal ≥ aporte mensal', missionType: 'crossover', isRequiredForPhase: true, orderIndex: 5, targetValue: null, targetSmMultiple: null, requiredDurationDays: null, description: 'O retorno mensal do portfólio (investido × taxa anual ÷ 12) ultrapassa o valor do aporte mensal.' },
    { phaseId: 4, slug: 'meta-300k', title: 'Atingir R$ 300.000 investidos', missionType: 'portfolio_value', isRequiredForPhase: true, orderIndex: 6, targetValue: '300000.00', targetSmMultiple: null, requiredDurationDays: null, description: 'O Ponto de Cruzamento provavelmente já ficou para trás.' },
    { phaseId: 5, slug: 'meta-500k', title: 'Atingir R$ 500.000 investidos', missionType: 'portfolio_value', isRequiredForPhase: true, orderIndex: 1, targetValue: '500000.00', targetSmMultiple: null, requiredDurationDays: null, description: 'Meio milhão. O portfólio gera mais por mês do que a maioria dos salários no Brasil.' },
    { phaseId: 5, slug: 'renda-passiva-1-5sm', title: 'Renda passiva mensal ≥ 1,5× salário mínimo', missionType: 'passive_income_sm', isRequiredForPhase: true, orderIndex: 2, targetValue: null, targetSmMultiple: '1.5', requiredDurationDays: null, description: 'A renda passiva começa a ser sentida de forma concreta no orçamento.' },
    { phaseId: 5, slug: 'oito-ativos-tres-categorias', title: 'Carteira com pelo menos 8 ativos em 3 categorias', missionType: 'behavioral', isRequiredForPhase: true, orderIndex: 3, targetValue: null, targetSmMultiple: null, requiredDurationDays: null, description: 'Diversificação real: pelo menos 8 ativos em ao menos 3 categorias distintas.' },
    { phaseId: 5, slug: 'renda-passiva-2sm', title: 'Renda passiva mensal ≥ 2× salário mínimo', missionType: 'passive_income_sm', isRequiredForPhase: true, orderIndex: 4, targetValue: null, targetSmMultiple: '2.0', requiredDurationDays: null, description: 'Um segundo "salário" gerado pelo patrimônio, sem trabalho adicional.' },
    { phaseId: 5, slug: 'meta-750k', title: 'Atingir R$ 750.000 investidos', missionType: 'portfolio_value', isRequiredForPhase: true, orderIndex: 5, targetValue: '750000.00', targetSmMultiple: null, requiredDurationDays: null, description: 'Três quartos do caminho para o primeiro milhão.' },
    { phaseId: 6, slug: 'renda-passiva-3sm', title: 'Renda passiva mensal ≥ 3× salário mínimo', missionType: 'passive_income_sm', isRequiredForPhase: true, orderIndex: 1, targetValue: null, targetSmMultiple: '3.0', requiredDurationDays: null, description: '3× SM cobre um padrão de vida básico-confortável na maioria das cidades brasileiras.' },
    { phaseId: 6, slug: 'meta-1M', title: 'Atingir R$ 1.000.000 investidos', missionType: 'portfolio_value', isRequiredForPhase: true, orderIndex: 2, targetValue: '1000000.00', targetSmMultiple: null, requiredDurationDays: null, description: 'O primeiro milhão. Marco simbólico e matemático.' },
    { phaseId: 6, slug: 'passiva-cobre-50-despesas', title: 'Renda passiva cobre pelo menos 50% das despesas mensais', missionType: 'behavioral', isRequiredForPhase: true, orderIndex: 3, targetValue: null, targetSmMultiple: null, requiredDurationDays: null, description: 'Você precisa do trabalho apenas para cobrir metade das contas.' },
    { phaseId: 6, slug: 'renda-passiva-3-5sm', title: 'Renda passiva mensal ≥ 3,5× salário mínimo', missionType: 'passive_income_sm', isRequiredForPhase: true, orderIndex: 4, targetValue: null, targetSmMultiple: '3.5', requiredDurationDays: null, description: 'Conforto crescente.' },
    { phaseId: 6, slug: 'imovel-ou-equivalente', title: 'Imóvel próprio quitado ou renda passiva superior ao custo de moradia', missionType: 'behavioral', isRequiredForPhase: false, orderIndex: 5, targetValue: null, targetSmMultiple: null, requiredDurationDays: null, description: 'Eliminar o maior custo fixo da vida.' },
    { phaseId: 7, slug: 'renda-passiva-5sm', title: 'Renda passiva mensal ≥ 5× salário mínimo', missionType: 'passive_income_sm', isRequiredForPhase: true, orderIndex: 1, targetValue: null, targetSmMultiple: '5.0', requiredDurationDays: null, description: '5× SM: padrão de vida confortável em qualquer região brasileira, sustentado pelo patrimônio.' },
    { phaseId: 7, slug: 'meta-1-5M', title: 'Atingir R$ 1.500.000 investidos', missionType: 'portfolio_value', isRequiredForPhase: true, orderIndex: 2, targetValue: '1500000.00', targetSmMultiple: null, requiredDurationDays: null, description: 'O portfólio cresce mais rápido do que você consegue gastar a renda passiva.' },
    { phaseId: 7, slug: 'passiva-cobre-100-despesas', title: 'Renda passiva cobre 100% das despesas mensais', missionType: 'behavioral', isRequiredForPhase: true, orderIndex: 3, targetValue: null, targetSmMultiple: null, requiredDurationDays: null, description: 'Trabalho é 100% opcional do ponto de vista financeiro.' },
    { phaseId: 7, slug: 'portfolio-cresce-apos-saques', title: 'Portfólio ainda cresce após sacar a renda passiva (3 meses)', missionType: 'behavioral', isRequiredForPhase: true, orderIndex: 4, targetValue: null, targetSmMultiple: null, requiredDurationDays: null, description: 'Verificado por 3 meses: após retirar toda a renda passiva, o valor total ainda aumentou.' },
    { phaseId: 7, slug: 'renda-5sm-seis-meses', title: 'Manter renda passiva ≥ 5× salário mínimo por 6 meses consecutivos', missionType: 'habit', isRequiredForPhase: true, orderIndex: 5, targetValue: null, targetSmMultiple: null, requiredDurationDays: 180, description: 'Consistência confirmada: não foi sorte, é o novo padrão.' },
    { phaseId: 8, slug: 'renda-passiva-7sm', title: 'Renda passiva mensal ≥ 7× salário mínimo', missionType: 'passive_income_sm', isRequiredForPhase: true, orderIndex: 1, targetValue: null, targetSmMultiple: '7.0', requiredDurationDays: null, description: '7× SM: padrão excelente em qualquer cidade brasileira, com sobra para reinvestir.' },
    { phaseId: 8, slug: 'meta-2M', title: 'Atingir R$ 2.000.000 investidos', missionType: 'portfolio_value', isRequiredForPhase: true, orderIndex: 2, targetValue: '2000000.00', targetSmMultiple: null, requiredDurationDays: null, description: 'Dois milhões. O portfólio gera mais do que você retira.' },
    { phaseId: 8, slug: 'portfolio-cresce-12-meses', title: 'Portfólio cresce após saques por 12 meses consecutivos', missionType: 'behavioral', isRequiredForPhase: true, orderIndex: 3, targetValue: null, targetSmMultiple: null, requiredDurationDays: null, description: 'Um ano completo: você viveu dos rendimentos e o patrimônio ainda aumentou.' },
    { phaseId: 8, slug: 'renda-7sm-seis-meses', title: 'Manter renda passiva ≥ 7× salário mínimo por 6 meses consecutivos', missionType: 'habit', isRequiredForPhase: true, orderIndex: 4, targetValue: null, targetSmMultiple: null, requiredDurationDays: 180, description: 'A renda elevada não foi sorte — é o novo patamar permanente.' },
    { phaseId: 8, slug: 'fire-confirmado', title: 'FIRE confirmado: nunca mais precisou trabalhar por necessidade financeira', missionType: 'behavioral', isRequiredForPhase: true, orderIndex: 5, targetValue: null, targetSmMultiple: null, requiredDurationDays: null, description: 'O Boss Final foi derrotado. Soberania total sobre seu tempo.' },
  ]

  for (const mission of missions) {
    await prisma.mission.upsert({ where: { slug: mission.slug }, update: mission, create: mission })
  }

  console.log(`✅ Seed concluído! ${phases.length} fases e ${missions.length} missões.`)
}

if (require.main === module || process.argv[1]?.endsWith('seed.ts')) {
  seedDatabase()
    .catch(e => { console.error(e); process.exit(1) })
    .finally(() => prisma.$disconnect())
}
